SinusSkateboards.UI/Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SinusSkateboards.UI.Pages
{
    [BindProperties]
    public class LoginModel : PageModel
    {
        private readonly SignInManager<IdentityUser> signInManager;

        [Required(ErrorMessage = "Username is missing")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Password is missing")]
        public string Password { get; set; }

        public LoginModel(SignInManager<IdentityUser> signInManager)
        {
            this.signInManager = signInManager;
        }

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                //Sign in user

                var result = await signInManager.PasswordSignInAsync(Username, Password, false, false);

                if (result.Succeeded)
                {
                    return RedirectToPage("/Admin/Index");
                }
            }

            return Page();
        }
        public async Task<IActionResult> OnPostLogout()
        {
            //Sign out user

            await signInManager.SignOutAsync();

            return RedirectToPage("/Index");
        }
    }
}

SinusSkateboards.UI/Pages/Products/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using SinusSkateboards.DAL;
using SinusSkateboards.DTO.Models;

namespace SinusSkateboards.UI.Pages.Products
{
    public class IndexModel : PageModel
    {
        private readonly SinusDbContext context;
        [BindProperty(SupportsGet = true)]
        public List<ProductModel> ProductList { get; set; }
        [BindProperty(SupportsGet = true)]
        public string SearchString { get; set; }

        public IndexModel(SinusDbContext context)
        {
            this.context = context;
        }
        public void OnGet()
        {
            ProductList = context.Products.ToList();
        }
        public void OnGetCategory(int id)
        {
            ProductList = context.Products.Where(x => x.CategoryId == id).ToList();
        }
        public IActionResult OnGetAddToCart(int id)
        {
            ProductModel productToAdd = context.Products.Include(x => x.Category).FirstOrDefault(x => x.Id == id);

            CartModel cart = new CartModel();

            string stringCart = HttpContext.Session.GetString("CookieCart");

            if (!String.IsNullOrEmpty(stringCart))
            {
                cart = JsonConvert.DeserializeObject<CartModel>(stringCart);
            }

            if (!cart.ProductsInCart.Where(x => x.Product.Id == id).Any())
            {
                cart.ProductsInCart.Add(new CartProductModel() { Product = productToAdd, Quantity = 1 });                
            }
            else
            {
                cart.ProductsInCart.FirstOrDefault(x => x.Product.Id == id).Quantity++;
            }

            stringCart = JsonConvert.SerializeObject(cart);

            HttpContext.Session.SetString("CookieCart", stringCart);

            return RedirectToPage("./Index");
        }
        public void OnPostSearch(string searchString)
        {
            if (SearchString != null)
            {
                ProductList = context.Products.Include(x => x.Category).Where(x => x.Title.ToUpper().Contains(SearchString.ToUpper()) || x.Category.Name.ToUpper().Contains(SearchString.ToUpper()) || x.Colour.ToUpper().Contains(SearchString.ToUpper())).ToList();
            }
            else
            {
                ProductList = context.Products.ToList();
            }
        }
    }
}

SinusSkateboards.UI/Pages/Shared/_CartBadge.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{
    @using Newtonsoft.Json;
    @using Microsoft.AspNetCore.Http;
    @using SinusSkateboards.DTO.Models

    string stringCart = HttpContextAccessor.HttpContext.Session.GetString("CookieCart");

    CartModel cookieCart = new CartModel();

    if (!String.IsNullOrEmpty(stringCart))
    {
        cookieCart = JsonConvert.DeserializeObject<CartModel>(stringCart);
    }
    if (cookieCart.ProductsInCart != null)
    {
        if (cookieCart.ProductsInCart.Any())
        {
            int itemsTotal = 0;
            foreach (var productDetail in cookieCart.ProductsInCart)
            {
                itemsTotal += productDetail.Quantity;
            }
            <span class="cart-counter-badge d-flex align-items-center justify-content-center font-weight-bold bg-dark disabled">
                @itemsTotal
            </span>
        }
    }
}

SinusSkateboards.UI/Pages/Shared/_CategoriesDrop.cshtml
@using SinusSkateboards.DAL
@using SinusSkateboards.DTO.Models
@using System.Linq

@inject SinusDbContext _context
@{
    List<CategoryModel> Categories = _context.Categories.ToList();

    <div class="dropdown h-100">
        <button class="btn dropdown-toggle h-100" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            @foreach (var category in Categories)
            {
                <a class="dropdown-item" asp-page="/Products/Index" asp-page-handler="Category" asp-route-id="@category.Id">@category.Name</a>
            }
        </div>
    </div>
}

SinusSkateboards.UI/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SinusSkateboards</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons|Material+Icons+Outlined" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index"><img src="~/images/logos/sinus-logo-landscape-small.png" alt="Sinus Logo" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between align-content-center">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <form method="post" asp-page="/Login" asp-page-handler="Logout">
                                    <div class="input-group">
                                        <button type="submit" class="btn btn-danger">Logout</button>
                                    </div>
                                </form>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-page="/Admin/Index">Admin Page</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Products/Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <partial name="_CategoriesDrop" />
                        </li>
                        @if (ViewBag.HideCart == null)
                        {
                            <li class="nav-item ml-auto d-flex flex-column justify-content-center">
                                <a asp-area="" asp-page="/Cart/Index" class="cart position-relative d-inline-flex btn-link text-dark align-icon">
                                    <span class="material-icons">
                                        shopping_cart
                                    </span>
                                    <partial name="_CartBadge" />
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Sinus Skateboards - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SinusSkateboards.UI/Pages/Shared/_LayoutFrontPage.cshtml
<!DOCTYPE html>
<html lang="en" style="height: 100%;">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SinusSkateboards</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons|Material+Icons+Outlined" rel="stylesheet">
</head>
<body class="p-0 m-0" style="height: 100%;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow" style="height: 87px;">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index"><img src="~/images/logos/sinus-logo-landscape-small.png" alt="Sinus Logo" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between align-content-center">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <form method="post" asp-page="/Login" asp-page-handler="Logout">
                                    <div class="input-group">
                                        <button type="submit" class="btn btn-danger">Logout</button>
                                    </div>
                                </form>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-page="/Admin/Index">Admin Page</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Products/Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <partial name="_CategoriesDrop" />
                        </li>
                        @if (ViewBag.HideCart == null)
                        {
                            <li class="nav-item ml-auto d-flex flex-column justify-content-center">
                                <a asp-area="" asp-page="/Cart/Index" class="cart position-relative d-inline-flex btn-link text-dark align-icon">
                                    <span class="material-icons">
                                        shopping_cart
                                    </span>
                                    <partial name="_CartBadge" />
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    @RenderBody()

    <footer class="border-top footer text-muted bg-white">
        <div class="container">
            &copy; 2021 - Sinus Skateboards - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>